name: CI-CD-MAIN

on:
    push:
        branches:
            - main
        paths-ignore:
            - 'python/**'

env:
    TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

permissions:
    contents: write
    pull-requests: write

jobs:
    build-and-test:
        name: build & test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node.js, PNPM, and install dependencies
              uses: ./.github/actions/pnpm-install

            - name: Build all
              working-directory: ./typescript
              run: pnpm build

            - name: Test all
              working-directory: ./typescript
              run: pnpm test


    release-or-create-release-pr:
        name: Release
        runs-on: ubuntu-latest
        needs: [build-and-test]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js, PNPM, and install dependencies
              uses: ./.github/actions/pnpm-install

            - name: Add npm auth token to pnpm
              run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
              env:
                  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
                  
            - name: Version Packages
              working-directory: ./typescript
              run: pnpm change:version
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Clean Examples
              working-directory: ./typescript
              run: pnpm clean:examples && pnpm lint:fix

            - name: Build
              working-directory: ./typescript
              run: pnpm build:libs:prod

            - name: Publish Snapshot Release
              working-directory: ./typescript
              run: pnpm change:publish
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
